# Author: David Oniani <onianidavid@gmail.com>
# Description: mise configuration file
# License: MIT

[tools]
go = "1.25.5"
lua = "5.4.8"
node = "25.2.1"
python = "3.14.2"
rust = "1.91.1"

[settings]
node = { gpg_verify = false }
python = { default_packages_file = "~/.config/mise/requirements.txt" }
